### ISSUE TITLE
int -> int32_t

### ISSUE THREAD

**Issue by rdiez** [boostorg/chrono#31]
In this routine:

inline int32_t days_from_1970(int32_t year)
    {
      static const int days_from_0_to_1970 = days_from_0(1970);
      return days_from_0(year) - days_from_0_to_1970;
}

Shouldn't type "int" above (for variable 'days_from_0_to_1970') actually be "int32_t"?

**Comment by viboes** [comment]
yes :)

**Comment by viboes** [comment]
https://github.com/boostorg/chrono/commit/ab84c68b6e49babfe3068db380d77de8a30931a6

**Comment by jeking3** [comment]
This has milestone 1.70 but it is in 1.69 beta 1.

**Comment by viboes** [comment]
Yes, you are right.
