### ISSUE TITLE
find little question

### ISSUE THREAD

**Issue by AsteriskZuo** [boostorg/chrono#46]
boost/chrono/round.hpp :

The header file is referenced repeatedly.

`
#ifndef BOOST_CHRONO_ROUND_HPP
#define BOOST_CHRONO_ROUND_HPP

#include <boost/chrono/duration.hpp>
#include <boost/chrono/duration.hpp>
//#include <boost/chrono/typeof/boost/chrono/chrono.hpp>
`

**Comment by viboes** [comment]
A PR is more than welcome

**Comment by AsteriskZuo** [comment]
I don't understand what you're saying. I found it occasionally. It's not public relations.
